import i18n from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    debug: true,
    fallbackLng: "en",
    returnObjects: true,
    resources: {
      en: {
        translation: {
          sideBar: {
            line1: "Account",
            line2: "Employee",
            line3: "Skill",
            line4: "Position",
            line5: "Project",
            line7: "Sign out",
          },
          account: {
            searchAccount: "Search by Email",
            clearAccount: "Clear",
            addAccount: "Add Account",
            emailAccount: "Email",
            actionAccount: "Action",
            editAccount: "Edit",
            deleteAccount: "Delete",
            passwordAccount: "Password",
            employeeAccount: "Employee",
            savedAccount: "Save",
            cancelAccount: "Cancel",
            statusAccount: "Status",
            status1: "Active",
            status2: "Inactive",
            statusEdit: "Account edited successfully",
            statusDelete: "Account deleted successfully",
            statusAdd: "Account added successfully",
            confirm1: "Sure to delete?",
            confirm2: "Please input the Email!",
            confirm3: "Please input the Password!",
            confirm4: "Please select an Employee!",
            confirm5: "Please input Email!",
            confirm6: "Please input Password!",
            confirm7: "Please input ",
            confirm8: "An unexpected error occurred!",
            confirm9:
              "Permission denied: You do not have the necessary role to perform this action!",
            holder: "Select an employee",
            error: "Error!",
            load: "Loading",
            empty: "No Data",
            page: "Page",
            noAccount: "No.",
            nameAccount: "Name",
            validEmail: "The input is not valid E-mail!",
          },
          employee: {
            addEmployee: "Add Employee",
            searchEmployee: "Search by name",
            clearEmployee: "Clear",
            editEmployee: "Edit",
            nameEmployee: "Name",
            phoneEmployee: "Phone",
            statusEmployee: "Status",
            positionEmployee: "Position",
            actionEmployee: "Action",
            noEmployee: "No.",
            dobEmployee: "Date of Birth",
            genderEmployee: "Gender",
            status1: "Involved",
            status2: "Inactive",
            status3: "Available",
            allAccount: "All Account",
            hasAccount: "Has Account",
            noAccount: "No Account",
            selectposition: "Select Position",
            selectdob: "Select Date",
            male: "Male",
            female: "Female",
            saveEmployee: "Save",
            cancelEmployee: "Cancel",
            confirm1: "Please input the Name!",
            confirm2: "Please enter your Phone number!",
            confirm3: "Please input the Birthday!",
            confirm4: "Please choose the Gender!",
            confirm5: "Please select a Position!",
            confirm6: "Please enter a valid Phone number!",
            confirm7: "Please select a Status!",
            confirm8: "You cannot change status from Involved to Inactive",
            confirm9: "Please input Email!",
            confirm10: "The input is not valid E-mail!",
            confirm11: "Are you sure to set employee",
            confirm12: "as Inactive?",
            statusAdd: "Account added successfully!",
            statusEdit: "Account edited successfully!",
            detail: "Employee Detail",
            page: "Page",
            load: "Loading",
            empty: "No Data",
            export: "Export Employees List",
            noPosition: "No Postion",
            delete: "Delete",
            yes: "Yes",
            no: "No",
            cv: "Export CV",
            skill: "Skills",
            selectSkill: "Select skills",
            confirm13: "An unexpected error occurred!",
            confirm14:
              "Permission denied: You do not have the necessary role to perform this action!",
            updateStatus:
              "Only employees with status 'Available' can be deleted.",
            only: "Employee status updated to Inactive.",
            filter: "Filter by account status",
            idCard: "ID Card",
            infor: "Personal Information",
            project: "Projects",
            editProfile: "Edit Profile",
            description: "Description",
            noFile: "No file selected!",
            failCanvas: "Failed to get cropped Canvas!",
            failConvert: "Failed to convert Canvas to Blob!",
            uploadFail: "File upload failed",
            image: "Image updated successfully",
            picture: "Edit Profile Picture",
            pic1: "Click or drag file to this area to upload",
            pic2: "Support for a single upload. Strictly prohibited from uploadingcompany data or other banned files.",
          },
          skill: {
            addSkill: "Add New Skill",
            tech: "Technologies",
            languageProgram: "Programming Languages",
            search: "Search",
            name: "Name",
            no: "No",
            category: "Category",
            status: "Status",
            action: "Actions",
            edit: "Edit",
            delete: "Delete",
            save: "Save",
            cancle: "Cancel",
            confirm1: "Please input Name!",
            confirm2: "Please choose a Category!",
            statusAdd: "Skill created successfully!",
            statusEdit: "Skill updated successfully!",
            statusDelete: "Skill deleted successfully!",
            statusFail: "Fail!",
            active: "Active",
            inactive: "Inactive",
            page: "Page",
          },
          project: {
            addProject: "Add Project",
            search: "Search Project",
            viewDelete: "View Deleted Projects",
            name: "Project Name",
            description: "Description",
            technology: "Technology",
            date: "Date Range",
            dateStart: "Start Date",
            dateEnd: "End Date",
            status: "Status",
            action: "Action",
            edit: "Edit",
            delete: "Delete",
            ok: "Ok",
            save: "Save",
            clear: "Clear",
            cancle: "Cancel",
            confirm1: "Please input Project name!",
            confirm2: "Please select Technologies!",
            confirm3: "Please select Date Range!",
            confirm4: "Are you sure to delete this project?",
            confirm5: "Select Employee",
            selectTech: "Select Technologies",
            statusAdd: "Added Successful!",
            statusEdit: "Edited Successful!",
            statusDelete: "Deleted Successful!",
            statusFail: "Fail!",
            onGoing: "Ongoing",
            notStart: "Not Started",
            complete: "Completed",
            page: "Page",
            noDelete: "No deleted projects found",
            noProject: "Project not found",
            resProject: "Project restored successfully!",
            history: "Delete History",
            employee: "Employee",
            restore: "Restore",
            export: "Export Project List",
            no: "No.",
            manager: "Project Manager",
            employeeName: "Employee Name",
            role: "Role",
            projectDetail: "Project Detail",
            editRole: "Edit Role",
            confirm6: "Select a role",
            notAssign: "Not Assigned",
            noRole: "No Role",
            updateRole: "Role updated successfully!",
            failRole: "Failed to update role:",
            missRole: "Missing project ID or employee ID!",
            validRole: "Validate Failed:",
            errorLoad: "Error loading project details. Please try again later.",
            descriptionP: "Please input the description",
            nameP: "Please input the name",
          },
          position: {
            no: "No.",
            name: "Name",
            description: "Description",
            status: "Status",
            action: "Action",
            search: "Search by name",
            clear: "Clear",
            addProject: "Add Position",
            edit: "Edit",
            delete: "Delete",
            save: "Save",
            cancle: "Cancel",
            confirm1: "Please input Name!",
            confirm2: "Please input Description!",
            confirm3: "Are you sure to delete this postion?",
            page: "Page",
            status1: "Active",
            status2: "Inactive",
            statusAdd: "Added Successful!",
            statusEdit: "Edited Successful!",
            statusDelete: "Deleted Successful!",
            noProject: "No data Position",
            please: "Please input",
          },
        },
      },
      vi: {
        translation: {
          sideBar: {
            line1: "Tài Khoản",
            line2: "Nhân Viên",
            line3: "Kĩ Năng",
            line4: "Vị TrÍ",
            line5: "Dự Án",
            line7: "Đăng Xuất",
          },
          account: {
            searchAccount: "Tìm Kiếm Bằng Email",
            clearAccount: "Làm Mới",
            addAccount: "Thêm Tài Khoản",
            emailAccount: "Email",
            actionAccount: "Tác Vụ",
            editAccount: "Chỉnh Sửa",
            deleteAccount: "Xóa",
            passwordAccount: "Mật Khẩu",
            employeeAccount: "Nhân Viên",
            savedAccount: "Lưu",
            cancelAccount: "Hủy Bỏ",
            statusAccount: "Trạng Thái",
            status1: "Hoạt Động",
            status2: "Ngừng Hoạt Động",
            statusEdit: "Chỉnh sửa tài khoản thành công",
            statusDelete: "Xóa tài khoản thành công",
            statusAdd: "Thêm tài khoản thành công",
            confirm1: "Xác Nhận Xóa",
            confirm2: "Vui lòng nhập Email!",
            confirm3: "Vui lòng nhập Mật khẩu",
            confirm4: "Vui lòng chọn Nhân viên!",
            confirm5: "Vui lòng nhập Email!",
            confirm6: "Vui lòng nhập Mật khẩu!",
            confirm7: "Vui lòng nhập",
            confirm8: "Đã xảy ra lỗi không mong muốn!",
            confirm9:
              "Quyền bị từ chối: Bạn không có vai trò cần thiết để thực hiện hành động này.",
            holder: "Chọn Nhân viên",
            error: "Lỗi!",
            load: "Đang tải",
            empty: "Không có dữ liệu",
            page: "Trang",
            noAccount: "Số Thứ Tự",
            nameAccount: "Tên",
            validEmail: "Email không hợp lệ!",
          },
          employee: {
            addEmployee: "Thêm Nhân Viên",
            searchEmployee: "Tìm kiếm bằng tên",
            clearEmployee: "Làm Mới",
            editEmployee: "Chỉnh Sửa",
            nameEmployee: "Tên",
            phoneEmployee: "Số Điện Thoại",
            statusEmployee: "Trạng Thái",
            positionEmployee: "Vị Trí",
            actionEmployee: "Tác Vụ",
            noEmployee: "Số Thứ Tự",
            dobEmployee: "Ngày sinh",
            genderEmployee: "Giới tính",
            status1: "Đang tham gia",
            status2: "Không hoạt động",
            status3: "Có sẵn",
            allAccount: "Tất Cả Tài Khoản",
            hasAccount: "Có Tài Khoản",
            noAccount: "Không Có Tài Khoản",
            selectposition: "Chọn Vị Trí",
            selectdob: "Chọn ngày sinh",
            male: "Nam",
            female: "Nữ",
            saveEmployee: "Lưu",
            cancelEmployee: "Hủy Bỏ",
            confirm1: "Vui lòng nhập tên!",
            confirm2: "Vui lòng nhập số điện thoại!",
            confirm3: "Vui lòng nhập ngày sinh!",
            confirm4: "Vui lòng nhập giới tính!",
            confirm5: "Vui lòng nhập vị trí!",
            confirm6: "Vui lòng nhập chính xác số điện thoại",
            confirm7: "Vui lòng nhập trạng thái!",
            confirm8:
              "Bạn không thể thay đổi trạng thái từ Đang tham gia liên quan sang Không hoạt động",
            confirm9: "Vui lòng nhập email!",
            confirm10: "Sai cú pháp!",
            confirm11: "Chắc chắn cài đặt nhân viên",
            confirm12: "thành Không hoạt động?",
            statusAdd: "Tạo nhân viên thành công!",
            statusEdit: "Chỉnh sửa nhân viên thành công!",
            detail: "Thông tin Nhân viên",
            page: "Trang",
            load: "Đang tải",
            empty: "Không có dữ liệu",
            export: "Tải danh sách Nhân viên",
            noPosition: "Không",
            delete: "Xóa",
            yes: "Có",
            no: "Không",
            cv: "Tải CV",
            skill: "Kĩ Năng",
            selectSkill: "Chọn Kĩ năng",
            confirm13: "Đã xảy ra lỗi không mong muốn!",
            confirm14:
              "Quyền bị từ chối: Bạn không có vai trò cần thiết để thực hiện hành động này.",
            updateStatus:
              "Chỉ những Nhân viên có Trạng thái 'Có sẵn' mới có thể bị xóa.",
            only: "Trạng thái Nhân viên được cập nhật thành Không hoạt động.",
            filter: "Lọc theo Trạng thái Tài khoản",
            idCard: "Thẻ ID",
            project: "Dự Án",
            editProfile: "Chỉnh sửa Hồ sơ",
            description: "Mô tả",
            infor: "Thông tin Cá nhân",
            noFile: "Không có tập tin được chọn!",
            failCanvas: "Không thể cắt Canvas!",
            failConvert: "Không thể chuyển đổi Canvas thành Blob!",
            uploadFail: "Tải tệp lên không thành công!",
            image: "Đã cập nhật hình ảnh thành công",
            picture: "Chỉnh sửa ảnh hồ sơ",
            pic1: "Nhấp hoặc kéo tệp vào khu vực này để tải lên",
            pic2: "Hỗ trợ tải lên một lần. Việc tải lên dữ liệu công ty hoặc các tập tin bị cấm khác đều bị nghiêm cấm.",
          },
          skill: {
            addSkill: "Thêm Kĩ Năng",
            tech: "Công Nghệ",
            languageProgram: "Ngôn Ngữ Lập Trình",
            search: "Tìm kiếm",
            name: "Tên",
            no: "Số Thứ Tự",
            category: "Danh Mục",
            status: "Trạng Thái",
            action: "Tác Vụ",
            edit: "Chỉnh Sửa",
            delete: "Xóa",
            save: "Lưu",
            cancle: "Hủy Bỏ",
            confirm1: "Vui lòng nhâp Tên!",
            confirm2: "Vui lòng chọn Danh mục!",
            statusAdd: "Thêm thành công!",
            statusEdit: "Chỉnh sửa thành công!",
            statusDelete: "Xóa thành công!",
            statusFail: "Thất bại!",
            active: "Hoạt Động",
            inactive: "Không Hoạt Động",
            page: "Trang",
          },
          project: {
            addProject: "Thêm Dự Án",
            search: "Tìm kiếm Dự Án",
            viewDelete: "Lịch Sử Xóa",
            name: "Tên Dự Án",
            description: "Mô Tả",
            technology: "Công Nghệ",
            date: "Phạm vi Ngày",
            dateStart: "Ngày bắt đầu",
            dateEnd: "Ngày kết thúc",
            status: "Trạng Thái",
            action: "Tác Vụ",
            edit: "Chỉnh Sửa",
            delete: "Xóa",
            clear: "Làm Mới",
            save: "Lưu",
            cancle: "Hủy Bỏ",
            ok: "Xác Nhận",
            confirm1: "Vui lòng nhâp Tên!",
            confirm2: "Vui lòng chọn Công Nghệ!",
            confirm3: "Vui lòng chọn Phạm vi Ngày!",
            confirm4: "Xác Nhận Xóa?",
            confirm5: "Thêm Nhân Viên",
            selectTech: "Chọn Công Nghệ",
            statusAdd: "Thêm thành công!",
            statusEdit: "Chỉnh sửa thành công!",
            statusDelete: "Xóa thành công!",
            statusFail: "Thất bại!",
            onGoing: "Đang Triển Khai",
            notStart: "Chưa Bắt Đầu",
            complete: "Hoàn Thành",
            page: "Trang",
            noDelete: "Không có Dự Án đã xóa",
            noProject: "Không có Dự án",
            resProject: "Hoàn tác Dự án thành công!",
            history: "Lịch Sử Xóa",
            employee: "Nhân Viên",
            comfirm5: "Chọn Nhân viên",
            restore: "Hoàn tác",
            export: "Tải danh sách Dự án",
            no: "Số Thứ Tự",
            manager: "Quản lí Dự án",
            employeeName: "Tên Nhân viên",
            role: "Vai trò",
            projectDetail: "Thông tin Dự Án",
            editRole: "Chỉnh sửa Vai trò",
            confirm6: "Vui lòng chọn vai trò",
            selectRole: "Chọn một vai trò",
            notAssign: "Không được phân công",
            noRole: "Không có Vai trò",
            updateRole: "Cập nhật Vai trò thành công!",
            failRole: "Không cập nhật được vai trò:",
            missRole: "Thiếu ID Dự án hoặc ID Nhân viên",
            validRole: "Xác thực thất bại:",
            errorLoad: "Lỗi tải xuống. Vui lòng thử lại sau!",
            descriptionP: "Vui lòng nhập mô tả!",
            nameP: "Vui lòng nhâp Tên!",
          },
          position: {
            no: "Số Thứ Tự",
            name: "Tên Vị Trí",
            description: "Mô Tả",
            status: "Trạng Thái",
            action: "Tác Vụ",
            search: "Tìm kiếm Vị trí",
            clear: "Làm Mới",
            addProject: "Thêm Vị trí",
            edit: "Chỉnh Sửa",
            delete: "Xóa",
            save: "Lưu",
            cancle: "Hủy Bỏ",
            confirm1: "Vui lòng nhâp Tên!",
            confirm2: "Vui lòng nhập mô tả!",
            confirm3: "Xác Nhận Xóa?",
            page: "Trang",
            status1: "Kích Hoạt",
            status2: "Không Kích Hoạt",
            statusFail: "Lỗi!",
            statusAdd: "Thêm thành công!",
            statusEdit: "Chỉnh sửa thành công!",
            statusDelete: "Xóa thành công!",
            noProject: "Không có Vị Trí",
            please: "Vui lòng nhập",
          },
        },
      },
    },
  });
